name = "ParametricInversion"
uuid = "6b46f060-7d60-4f37-b11d-8d056bd60d70"
authors = ["Zenna Tavares", "David Morejon"]
version = "0.1.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Mjolnir = "1154507a-7ac2-44fe-9f15-34617bca9db5"
ParametricInversionTestUtils = "c9df7d97-9b3b-4ef1-a62f-8dc2fdc1a53b"
Spec = "b8ccf107-3a88-5e0f-823b-b838c6a0f327"

[compat]
julia = "1"

[extras]
ParametricInversionTestUtils = "c9df7d97-9b3b-4ef1-a62f-8dc2fdc1a53b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "ParametricInversionTestUtils", "Random"]
